// ng/src/app/components/NavMenu.component.ts
const template=`
<nav>
	<b style="color:#900;font-size:1.5em;">MD EDIT</b>{{" "}}
	<a href="../">Vanilla</a>{{" "}}
	<a [href]="ve">Vue.js</a>{{" "}}
	<a [href]="br">Blazor</a>{{" "}}
	<a routerLinkActive="active" [routerLinkActiveOptions]="{exact:true}" routerLink="/">Angular</a>{{" "}}
	<a href="https://github.com/yosgspec/SimpleMarkdownEdit">GitHub</a>
</nav>

<style>
.active{
	color: #FF0000;
	font-weight: bold;
}
</style>
`;

import {Component} from "@angular/core";

@Component({
	selector: "NavMenu",
	templateUrl: template
})
export class NavMenuComponent{
	get ve(){return location.href.replace("/ng/","/ve/");}
	get br(){return location.href.replace("/ng/","/br/");}
}

// ve/src/components/NavMenu.vue
<template>
<nav>
	<b style="color:#090;font-size:1.5em;">MD EDIT</b>{{" "}}
	<a href="../">Vanilla</a>{{" "}}
	<router-link to="/">Vue.js</router-link>{{" "}}
	<a :href="br">Blazor</a>{{" "}}
	<a :href="ng">Angular</a>{{" "}}
	<a href="https://github.com/yosgspec/SimpleMarkdownEdit">GitHub</a>
</nav>
</template>

<style scoped>
.router-link-exact-active{
	color: #FF0000;
	font-weight: bold;
}
</style>

<script lang=ts>
import {Component,Watch,Vue} from "vue-property-decorator";

@Component
export default class NavMenu extends Vue{
	get br(){return location.href.replace("/ve/","/br/");}
	get ng(){return location.href.replace("/ve/","/ng/");}
}
</script>
